C = int(input('Cola         @ 10 : want to buy : '))
G = int(input('Green Tea    @ 12 : want to buy : '))
M = int(input('Milk         @ 15 : want to buy : '))
E = int(input('Energy Drink @ 20 : want to buy : '))
F = int(input('Fruit Juice  @ 22 : want to buy : '))
Cola = (C*10)
GreenTea = (G*12)
Milk = (M*15)
EnergyDrink = (E*20)
FruitJuice = (F*22)
Apr = (FruitJuice+EnergyDrink+Milk+GreenTea+Cola)
Vat = int(Apr*0.07)
print('Total piece of Cola         : ',C,('Total price : '),Cola)
print('Total piece of Green Tea    : ',G,('Total price : '),GreenTea)
print('Total piece of Milk         : ',M,('Total price : '),Milk)
print('Total piece of Energy Drink : ',E,('Total price : '),EnergyDrink)
print('Total piece of Fruit Juice  : ',F,('Total price : '),FruitJuice)
print('Total all piece : ',C+G+M+E+F)
print('Total all price : ',Apr)
print('Vat : ',Vat)
print('Total : ',Apr+Vat)