def main():
    infile = open('/Users/Python/Desktop/MyPython/final 2562-1/file-n-exceptions/philosophers.txt','r')
    line1 = infile.readline()
    line2 = infile.readline()
    line3 = infile.readline()
    line1 = line1.rstrip('\n')
    line2 = line2.rstrip('\n')
    line3 = line3.rstrip('\n')
    infile.close()
    print(line1)
    print(line2)
    print(line3)
    a = (len(line1.split()))
    b = (len(line2.split()))
    c = (len(line3.split()))
    total = a+b+c
    print(total)
main()